global:
  scrape_interval: 15s # How frequently to scrape targets by default.
  scrape_timeout: 10s # How long until a scrape request times out.
  evaluation_interval: 15s # How frequently to evaluate rules.

  external_labels:
    monitor: 'prometheus_tutorial'

rule_files:
  - /etc/prometheus/prometheus.rules.yml

# A scrape configuration
scrape_configs:
  - job_name: prometheus
    honor_labels: true
    honor_timestamps: true
    scheme: http
    scrape_interval: 50s
    scrape_timeout: 20s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
        labels:
          group: 'qa'

  - job_name: custom-python
    static_configs:
      - targets: ['localhost:8008']